### ISSUE TITLE
Assalomu alaykum Samanadar aka mana bu qismda hover holati berilmagan ekan bersak yaxshi bo'lardi

### ISSUE THREAD

**Issue by Kamol21** [Sayfudiinov-Samandar/bookmark#1]
![Screenshot from 2022-07-01 10-58-46](https://user-images.githubusercontent.com/101969290/176833411-4f4e97a7-5797-4b34-b505-62d08aec7896.png)

**Comment by Kamol21** [comment]
bu buttonda hover holatida borderi 1px bolib qolibdi maketdda 2px korsatilgan ekan shuni togirlab qoysak yaxshi bolardi
![Screenshot from 2022-07-01 11-05-39](https://user-images.githubusercontent.com/101969290/176834464-16e9c9b0-d789-4ef1-a20e-eeddf82b2ae4.png)

**Comment by Kamol21** [comment]
ulning chap tomonida default padding qolib ketibdi olib tashlasak yaxshi bolardi

![Screenshot from 2022-07-01 11-19-43](https://user-images.githubusercontent.com/101969290/176836003-dc04bc2b-7732-4bb2-b670-b15c4b1096cf.png)

**Comment by Sayfudiinov-Samandar** [comment]
hop rahmat endi tog'ilab qo'yaman
