### ISSUE TITLE
Bu joyda ortiqcha margin berilgan ekan shu navni ichiga olingan a linkni alohida qilib qo'ysak yaxshi bo'lardi va li'larni margin-right'lari ko'payib ketgan

### ISSUE THREAD

**Issue by Azamatjon0110** [Sayfudiinov-Samandar/bookmark#4]
![image](https://user-images.githubusercontent.com/105698184/176837663-f1012f45-466a-4a5a-8b3f-aed0a18142b5.png)

**Comment by Sayfudiinov-Samandar** [comment]
Bu joyda ekran qisqarganda bir birini ustiga chiq ketmasligi uchun margin berilgan.
