### ISSUE TITLE
bu joyida nuqtachalarni liga emas pga after deb yozib ketsak yaxshi bolardi

### ISSUE THREAD

**Issue by Kamol21** [Sayfudiinov-Samandar/bookmark#9]
![Screenshot from 2022-07-01 11-43-14](https://user-images.githubusercontent.com/101969290/176839870-b5275611-dd99-4b67-9c09-70526018c613.png)

**Comment by Sayfudiinov-Samandar** [comment]
ok to'g'irlandi
